{% set version = "0.9.0" %}  # PEP 386

{% set number = "2" %}
{% set cuda_enabled = cuda_compiler_version is not undefined and cuda_compiler_version == '11.0' %}
{% set build_ext = "cuda" if cuda_enabled else "cpu" %}
{% set build_string = "h{}_{}".format(PKG_HASH, number) %}
{% set build_string_ext = "{}_{}".format(build_string, build_ext) %}
{% set py_build_string_ext = "py{}{}_{}".format(CONDA_PY, build_string, build_ext) %}
{% set py_build_string = "py{}{}".format(CONDA_PY, build_string) %}
{% set install_base = "opt/hdk" %}
{% set llvm_version = "16" %}

# get smithy to play ball...
{% set libarrow = "13" if libarrow is undefined else libarrow %}

package:
  name: hdk
  version: {{ version }}

source:
  git_url: https://github.com/intel-ai/hdk
#  git_branch: release/v{{ version }}
#  git_rev: 798103ac37f9badd540b4f4508ca180162eeb654
#  url: https://github.com/intel-ai/hdk/archive/refs/tags/v{{ version }}.tar.gz
#  sha256: dc2e84db9536158f69de12e62d3d8d1ebcb45d4c3d35a42e54de771490a280ac

build:
  number: {{ number }}
  skip: true  # [not (linux64 or win64)]
  # hdk only support arrow >11
  skip: true  # [libarrow == "10.0.1"]

outputs:

  - name: pyhdk
    version: {{ version }}
    script: build-hdk.sh   # [not win]
    script: build-hdk.bat  # [win]
    build:
      string: {{ py_build_string_ext }}
      # some weird header interaction, but only on windows, and only
      # limited to oldest python with newest arrow --> skip it
      {% if libarrow.split(".")[0]|int > 12 %}
      skip: true  # [win and py==38]
      {% endif %}
      missing_dso_whitelist:
        - '*/libcuda.*'  # [cuda_compiler_version not in (undefined, "None")]
        - '*/libjvm.so'
      track_features:
        {{ "- arrow-cuda" if cuda_enabled else "" }}
      rpaths:
        - lib
        # path for libjvm.so searching
        - lib/server
        - lib/jvm/lib/server
        # fixes "overlinking check failed"
        - {{ install_base }}/lib64
    requirements:
      build:
        - cmake
        # c compiler is specified here to get run constraint pins correct, presumably..
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler("cuda") }}  # [cuda_compiler_version not in (undefined, "None")]
        - clangdev {{ llvm_version }}
        # clang++ is used for generating the bytecodes of extension functions
        - clangxx {{ llvm_version }}
        - llvmdev {{ llvm_version }}
        - make  # [not win]
        - maven
        - level-zero-devel  # [not win]
        - pkg-config  # [not win]
        - llvm-spirv {{ llvm_version }}  # [not win]
        - libllvmspirv {{ llvm_version }}  # [not win]
      host:
        - python
        - cython
        - numpy
        - tbb-devel
        - gflags  # [unix]
        - glog
        # Folly and fmt are mutially exclusive on linux but fmt is
        # requred on windows.
        - fmt  # [win]
        - folly >=2022.11.07.00  # [not win]
        - llvm {{ llvm_version }}
        - libboost-devel
        # one libarrow to pick up global pinning, one to select variant
        - libarrow
        - libarrow =*=*{{ build_ext }}
        # same here; one for pinning, one for additionally specifying lower bound
        - libsqlite
        - libsqlite >=3.40
        - pyarrow
        - zlib
      run:
        - pyarrow =*=*{{ build_ext }}
        - python
        - openjdk >=11
        - zlib
        - tbb
        - folly >=2022.11.07.00  # [not win]
        - llvm-spirv {{ llvm_version }}  # [not win]
        - level-zero  # [not win]
      run_constrained:
        - apache-arrow-proc =*={{ build_ext }}
        - cudatoolkit >=11.0  # [cuda_compiler_version not in (undefined, "None")]

    test:
      requires:
        - pytest
        - numpy
        - pandas
      imports:
        - pyhdk
      source_files:
        - python/tests/test_pyhdk_bindings.py
        - python/tests/test_pyhdk_sql.py
      commands:
        - python python/tests/test_pyhdk_bindings.py
        - python python/tests/test_pyhdk_sql.py

    about:
      home: https://github.com/intel-ai/hdk
      license: Apache-2.0
      license_family: APACHE
      license_file: LICENSE
      summary: oneHDK

      description: |
        oneHDK
      doc_url: https://github.com/intel-ai/hdk
      dev_url: https://github.com/intel-ai/hdk

about:
  home: https://github.com/intel-ai/hdk
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: oneHDK

  description: |
    oneHDK
  doc_url: https://github.com/intel-ai/hdk
  dev_url: https://github.com/intel-ai/hdk

extra:
  recipe-maintainers:
    - alexbaden
    - ienkovich
    - Garra1980
    - vlad-penkin
    - leshikus
