{% set version = "0.4.0" %}  # PEP 386
{% set number = "0" %}
{% set cuda_enabled = cuda_compiler_version is not undefined and cuda_compiler_version == '11.0' %}
{% set build_ext = "cuda" if cuda_enabled else "cpu" %}
{% set build_string = "h{}_{}".format(PKG_HASH, number) %}
{% set build_string_ext = "{}_{}".format(build_string, build_ext) %}
{% set py_build_string_ext = "py{}{}_{}".format(CONDA_PY, build_string, build_ext) %}
{% set py_build_string = "py{}{}".format(CONDA_PY, build_string) %}
{% set install_base = "opt/hdk" %}
{% set arrow_version = "11.*" %}
{% set arrow_proc_version = "3.*" %}
{% set llvm_version = "14" %}

package:
  name: hdk
  version: {{ version }}

source:
  git_url: https://github.com/intel-ai/hdk
  git_branch: main

build:
  number: {{ number }}
  skip: True  # [cuda_compiler_version not in (undefined, "None", "11.0")]
  skip: True  # [not linux64]

outputs:

  - name: pyhdk
    version: {{ version }}
    script: build-hdk.sh
    build:
      string: {{ py_build_string_ext }}
      skip: True  # [py not in (38, 39, 310)]
      missing_dso_whitelist:
        - '*/libcuda.*'  # [cuda_compiler_version not in (undefined, "None")]
        - '*/libjvm.so'
      track_features:
        {{ "- arrow-cuda" if cuda_enabled else "" }}
      rpaths:
        - lib
        # path for libjvm.so searching
        - lib/server
        - lib/jvm/lib/server
        # fixes "overlinking check failed"
        - {{ install_base }}/lib64
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        # c compiler is specified here to get run constraint pins correct, presumably..
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler("cuda") }}  # [cuda_compiler_version not in (undefined, "None")]
        - clangdev {{ llvm_version }}
        # clang++ is used for generating the bytecodes of extension functions
        - clangxx {{ llvm_version }}
        - cmake
        - llvmdev {{ llvm_version }}
        - make
        - maven
        - ninja
        - libsqlite
        - folly 2022.11.07.00
        - tbb-devel
      host:
        - arrow-cpp ={{ arrow_version }}=*{{ build_ext }}
        - boost-cpp
        - cython
        - glog
        - llvm {{ llvm_version }}
        - numpy
        - pyarrow ={{ arrow_version }}=*{{ build_ext }}
        - python
      run:
        - arrow-cpp-proc {{ arrow_proc_version }} {{ build_ext }}
        - pyarrow ={{ arrow_version }}=*{{ build_ext }}
        - python
        - openjdk 17.*
        - zlib
        - tbb
        - libsqlite
        - boost-cpp

      run_constrained:
        - arrow-cpp-proc {{ arrow_proc_version }} {{ build_ext }}
        - cudatoolkit >=11.0  # [cuda_compiler_version not in (undefined, "None")]

    test:
      requires:
        - pytest
        - numpy
        - pandas
      imports:
        - pyhdk
      source_files:
        - python/tests/test_pyhdk_bindings.py
        - python/tests/test_pyhdk_sql.py
      commands:
        - python python/tests/test_pyhdk_bindings.py
        - python python/tests/test_pyhdk_sql.py

    about:
      home: https://github.com/intel-ai/hdk
      license: Apache-2.0
      license_family: APACHE
      license_file: LICENSE
      summary: oneHDK

      description: |
        oneHDK
      doc_url: https://github.com/intel-ai/hdk
      dev_url: https://github.com/intel-ai/hdk

about:
  home: https://github.com/intel-ai/hdk
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: oneHDK

  description: |
    oneHDK
  doc_url: https://github.com/intel-ai/hdk
  dev_url: https://github.com/intel-ai/hdk

extra:
  recipe-maintainers:
    - alexbaden
    - ienkovich
    - Garra1980
    - vlad-penkin
    - leshikus
