# Intel GPU stack
# https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-jammy-arc.html
RUN wget -qO - https://repositories.intel.com/graphics/intel-graphics.key | \
    sudo gpg --dearmor --output /usr/share/keyrings/intel-graphics.gpg && \
    echo 'deb [arch=amd64,i386 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/graphics/ubuntu jammy arc' | \
    sudo tee  /etc/apt/sources.list.d/intel.gpu.jammy.list && \
    apt-get update && \
        apt-get install -y \
        intel-igc-cm \
        intel-level-zero-gpu \
        intel-media-va-driver-non-free \
        intel-opencl-icd \
        level-zero \
        level-zero-dev \
        libigc-dev \
        libigdfcl-dev \
        libigfxcmrt-dev \
        libmfx1 \
        --

RUN git clone -b llvm_release_120 https://github.com/KhronosGroup/SPIRV-LLVM-Translator.git && \
    mkdir SPIRV-LLVM-Translator/build && cd SPIRV-LLVM-Translator/build && \
    cmake -Wno-dev .. && make llvm-spirv -j`nproc` && make install

