#ifndef HETEROGENEOUSDATAKERNELS_EXECUTIONENGINE_H
#define HETEROGENEOUSDATAKERNELS_EXECUTIONENGINE_H

namespace hdk {

void test_function();

}

#endif  // HETEROGENEOUSDATAKERNELS_EXECUTIONENGINE_H
