# Cuda stack
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb && \
    dpkg -i cuda-keyring_1.0-1_all.deb && \
    apt-get update && \
    apt-get install -y cuda-toolkit-12-0 cuda-drivers-525 libarrow-cuda-dev=11.*

ENV PATH=/usr/local/cuda/bin${PATH:+:${PATH}}

