# Cuda stack
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb && \
    dpkg -i cuda-keyring_1.1-1_all.deb && \
    apt-get update && \
    apt-get install -y cuda-toolkit-12-2 cuda-drivers-535 libarrow-cuda-dev=13.*

ENV PATH=/usr/local/cuda/bin${PATH:+:${PATH}}

